name: Build and deploy Node.js app to Azure Web App - app-002-gen10-step3-1-node-oshima58

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: frontend   # ← 重要：frontend 配下で実行

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          # Azure App Service の既定と相性が良い LTS を推奨（20 か 22）
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: npm install, build, and test
        env:
          NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}
        run: |
          npm ci
          npm run build --if-present
          npm test --if-present

      # Next.js standalone をデプロイ用フォルダにまとめる
      - name: Prepare deploy artifact
        run: |
          rm -rf deploy
          mkdir -p deploy
          # standalone 一式と static をコピー
          cp -r .next/standalone/* ./deploy/
          mkdir -p ./deploy/.next
          cp -r .next/static ./deploy/.next/static
          # public 配下の静的ファイルも必要なら
          cp -r public ./deploy/public || true

      - name: Upload deploy artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: frontend/deploy   # ← deploy だけをアップロード

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .  # カレントに展開（./deploy ができる）

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-002-gen10-step3-1-node-oshima58'
          slot-name: 'Production'
          package: ./deploy          # ← 展開された deploy をそのまま送る
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_110A8B7038114DDA93FBF9F6FF08A8A0 }}

