name: Deploy Next.js POS App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install and Build
        env:
          NEXT_PUBLIC_API_ENDPOINT: /api
          NEXT_TELEMETRY_DISABLED: '1'
        run: |
          npm ci
          npm run build

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-002-gen10-step3-1-node-oshima58'
          package: frontend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
